dependencies:
        - binutils
        - ccache
        - clang
        - clangxx
        - cmake
        - docutils
        - gcc<15
        - gfortran<15
        - glew
        - glfw
        - gmp
        - gxx
        - lark-parser
        - libclang
        - libcxx
        - libmicrohttpd
        - libopenblas=*=*openmp*
        - llvm-openmp
        - matplotlib
        - netcdf4
        - numpy
        - pkg-config
        - pytest
        - python-build
        - scipy
        - setuptools
        - sphinx
        - sphinx-favicon
        - sphinx_rtd_theme
        - tqdm
        - xarray
        - zlib
        - mesa-libgl-devel-cos7-x86_64
        - libselinux-cos7-x86_64
        - libglvnd-glx-cos7-x86_64
        - libxext-cos7-x86_64
        - libxdamage-cos7-x86_64
        - libxcb-cos7-x86_64
        - libxfixes-cos7-x86_64
        - libxxf86vm-cos7-x86_64
        - libxau-cos7-x86_64
        - expat-cos7-x86_64
channels:
        - conda-forge
