
#include "f2c.h"

/* ~~~~~~~~~~~~ */
/* VERSION 1.2 */
/* ~~~~~~~~~~~~ */
/* Subroutine */ 
int disort_(integer *nlyr,
            float *dtauc, 
            float *ssalb, 
            float *pmom, 
            float *temper, 
            float *wvnmlo,
            float *wvnmhi,
            logical *usrtau,
            integer *ntau, 
            float *utau,
            integer *nstr,
            logical *usrang, 
            integer *numu, 
            float *umu,
            integer *nphi, 
            float *phi,
            integer *ibcnd,
            float *fbeam,
            float *umu0, 
            float *phi0, 
            float *fisot, 
            logical *lamber, 
            float *albedo, 
            float *hl, 
            float *btemp, 
            float *ttemp,
            float *temis, 
            logical *deltam, 
            logical *plank,
            logical *onlyfl,
            float *accur, 
            logical *prnt,
            char *header,
            integer *maxcly, 
            integer *maxulv,
            integer *maxumu, 
            integer *maxcmu, 
            integer *maxphi, 
            float *rfldir, 
            float *rfldn,
            float *flup,
            float *dfdt,
            float *uavg,
            float *uu,
            float *u0u, 
            float *albmed, 
            float *trnmed, 
            ftnlen header_len);

