/* Input / Output method functions. */

#include "arts.h"
#include "messages.h"
#include "file.h"
#include "md.h"

void VectorWriteToFile(// WS Output:
                       VECTOR& v,
                       // Control Parameters:
                       const string& filename)
{
  extern const string full_name;
  ofstream of;

  open_output_file(of, filename);
  of << "# Generated by "
     << full_name << ", "
     << __DATE__ << ", "
     << __TIME__ << "\n";

  of << "\"";
  // FIXME: Wo den Namen herbekommen?
}
