#include <auto_wsg.h>
#include <debug.h>

#include <iostream>
#include <string>

#include "workspace_agendas.h"
#include "workspace_groups.h"
#include "workspace_variables.h"

namespace {
const auto& wsg  = internal_workspace_groups();
const auto& vars = internal_workspace_variables();
const auto& ags  = internal_workspace_agendas();

void header(std::ostream& os) {
  os << R"--(#pragma once

//! auto-generated by make_auto_wsv.cpp

#include <format_tags.h>

#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

#include "auto_wsg.h"

#include <workspace_agenda_class.h>
#include <workspace_method_class.h>

struct WorkspaceVariableRecord {
  std::string desc;
  std::string type;
  std::optional<Wsv> default_value{};

  //! The dimensions this variable names, outermost first
  std::vector<std::string> dims{};

  //! The dimensions inside each element, for an array of equally shaped elements
  std::vector<std::string> inner_dims{};
};

const std::unordered_map<std::string, WorkspaceVariableRecord>& workspace_variables();

template <> struct std::formatter<WorkspaceVariableRecord> {
  format_tags tags;

  [[nodiscard]] constexpr auto& inner_fmt() { return *this; }

  [[nodiscard]] constexpr const auto& inner_fmt() const { return *this; }

  constexpr std::format_parse_context::iterator parse(std::format_parse_context& ctx) {
    return parse_format_tags(tags, ctx);
  }

  template <class FmtContext> FmtContext::iterator format(const WorkspaceVariableRecord& wsv, FmtContext& ctx) const {
    return tags.format(ctx,
                       "WorkspaceVariableRecord{"sv,
                       "\n  .desc="sv,
                       wsv.desc,
                       "\n  .type="sv,
                       wsv.type,
                       "\n  .default_value="sv,
                       wsv.default_value ? "true"sv : "false"sv,
                       "\n  .dims="sv,
                       wsv.dims,
                       "\n  .inner_dims="sv,
                       wsv.inner_dims,
                       "\n}"sv);
  }
};
)--";
}

void implementation(std::ostream& os) {
  const auto& wsv = internal_workspace_variables();
  const auto& wsa = internal_workspace_agendas();

  std::print(os,
             R"--(//! auto-generated by make_auto_wsv.cpp

#include "auto_wsv.h"

#include <workspace_agendas.h>
#include <workspace_variables.h>

)--");

  for (auto& [name, wsa] : internal_workspace_agendas()) {
    if (not wsa.enum_default.empty()) { std::println(os, "Agenda get_{}(const std::string_view);", name); }
  }

  std::print(os,
             R"--(

std::unordered_map<std::string, WorkspaceVariableRecord> workspace_variables_create() {{
  std::unordered_map<std::string, WorkspaceVariableRecord> vars;
  vars.reserve({});
)--",
             wsv.size() + 2 * wsa.size());

  const auto quoted_list = [](const std::vector<std::string>& v) {
    std::string out;
    for (const auto& x : v) out += std::format(R"({}"{}")", out.empty() ? "" : ", ", x);
    return out;
  };

  for (auto&& [name, record] : wsv) {
    std::print(
        os,
        R"(
  vars.emplace("{0}", WorkspaceVariableRecord{{
    .desc          = R"-WSV-({1})-WSV-",
    .type          = "{2}",
    .default_value = {3},
    .dims          = {{{4}}},
    .inner_dims    = {{{5}}}
  }});

)",
        name,
        record.desc,
        record.type,
        record.default_value.empty() ? "std::nullopt" : std::format("{}{{ {} }}", record.type, record.default_value),
        quoted_list(record.dims),
        quoted_list(record.inner_dims));
  }

  os << R"--(
  return vars;
}

const std::unordered_map<std::string, WorkspaceVariableRecord>& workspace_variables() {
  const static auto vars = workspace_variables_create();
  return vars;
}
)--";
}
}  // namespace

int main() try {
  std::ofstream head("auto_wsv.h");
  std::ofstream impl("auto_wsv.cpp");

  header(head);
  implementation(impl);
} catch (std::exception& e) {
  std::cerr << "Cannot create the automatic variables with error:\n\n" << e.what() << '\n';
  return 1;
}
