#include <auto_wsg.h>
#include <debug.h>
#include <mystring.h>

#include <algorithm>
#include <exception>
#include <format>
#include <iostream>
#include <ranges>
#include <stdexcept>
#include <string>

#include "workspace_dimensions.h"
#include "workspace_group_friends.h"
#include "workspace_groups.h"
#include "workspace_meta_methods.h"
#include "workspace_methods.h"
#include "workspace_variables.h"

namespace {
void scan_wsmr_for_errors(ArrayOfString& errors, const std::string& name, const WorkspaceMethodInternalRecord& wsmr) {
  const auto& wsv = internal_workspace_variables();

  if (wsmr.desc.size() == 0) { errors.push_back(std::format("No description for \"{}\"", name)); }

  if (wsmr.desc.back() not_eq '\n') {
    errors.push_back(std::format("Description for \"{}\" ends without a newline", name));
  }

  if (wsmr.author.size() == 0) { errors.push_back(std::format("No authors for \"{}\"", name)); }

  if (wsmr.gout.size() not_eq wsmr.gout_type.size() or wsmr.gout.size() not_eq wsmr.gout_desc.size()) {
    errors.push_back(std::format("Mismatch sizes of gout ({}), gout_type ({}), gout_des ({}), for \"{}\"",
                                 wsmr.gout.size(),
                                 wsmr.gout_type.size(),
                                 wsmr.gout_desc.size(),
                                 name));
  }

  for (auto& type : wsmr.gout_type) {
    if (not valid_wsg(type)) { errors.push_back(std::format(R"(Invalid gout_type for "{}": "{}")", name, type)); }
  }

  for (auto& gvar : wsmr.gout) {
    if (wsv.find(gvar) not_eq wsv.end()) {
      errors.push_back(std::format(R"(Invalid gout for "{}": "{}" - it is already a WSV)", name, gvar));
    }
  }

  if (wsmr.gin.size() not_eq wsmr.gin_type.size() or wsmr.gin.size() not_eq wsmr.gin_value.size() or
      wsmr.gin.size() not_eq wsmr.gin_desc.size()) {
    errors.push_back(std::format("Mismatch sizes of gin ({}), gin_type ({}), gin_value ({}), gin_desc ({}), for \"{}\"",
                                 wsmr.gin.size(),
                                 wsmr.gin_type.size(),
                                 wsmr.gin_value.size(),
                                 wsmr.gin_desc.size(),
                                 name));
  }

  for (auto& type : wsmr.gin_type) {
    if (not valid_wsg(type)) { errors.push_back(std::format(R"(Invalid gin_type for "{}": "{}")", '"', name, type)); }
  }

  for (auto& gvar : wsmr.gin) {
    if (wsv.find(gvar) not_eq wsv.end()) {
      errors.push_back(std::format(R"(Invalid gin for "{}": "{}" - it is already a WSV)", name, gvar));
    }
  }

  for (auto& var : wsmr.out) {
    if (wsv.find(var) == wsv.end()) {
      errors.push_back(std::format(R"(Invalid out for "{}": "{}" - it is not a WSV)", name, var));
    }
  }

  for (auto& var : wsmr.in) {
    if (wsv.find(var) == wsv.end()) {
      errors.push_back(std::format(R"(Invalid in for "{}": "{}" - it is not a WSV)", name, var));
    }
  }
}

ArrayOfString scan_for_errors() {
  const auto& wsm = internal_workspace_methods();

  ArrayOfString errors{};

  for (auto [name, wsmr] : wsm) {
    for (auto* types : {&wsmr.gout_type, &wsmr.gin_type}) {
      for (const auto& type : *types)
        for (auto item : split(type, ",")) {
          trim(item);
          if (not valid_wsg(item)) errors.push_back("Invalid group " + item + " in " + name);
        }
      for (auto& type : *types) type = split(type, ",").front();
    }
    scan_wsmr_for_errors(errors, name, wsmr);
  }

  return errors;
}

void signature(std::ostream& os, const std::string& name, const WorkspaceMethodInternalRecord& wsmr) try {
  os << wsmr.docstring() << '\n';

  os << wsmr.header(name) << ";\n";
} catch (std::exception& e) { throw std::runtime_error("Error in signature():\n\n" + std::string(e.what())); }

void header(std::ostream& os) try {
  const auto& wsm = internal_workspace_methods();

  os << R"--(#pragma once

//! auto-generated by make_auto_wsm.cpp

#include <string>
#include <vector>

#include "auto_wsg.h"

struct Workspace;

struct WorkspaceMethodRecord {
  std::vector<std::string> out;
  std::vector<std::string> in;
  std::unordered_map<std::string, Wsv> defs;
  std::function<void(Workspace&, const std::vector<std::string>&, const std::vector<std::string>&)> func;
};

const std::unordered_map<std::string, WorkspaceMethodRecord>& workspace_methods();

)--";

  for (auto& [name, wsmr] : wsm) {
    signature(os, name, wsmr);
    os << '\n';
  }
} catch (std::exception& e) { throw std::runtime_error("Error in header():\n\n" + std::string(e.what())); }

std::string error_signature(const std::string& name, const WorkspaceMethodInternalRecord& wsmr) {
  const auto& wsvs = internal_workspace_variables();

  std::size_t type_spaces = 0;
  for (auto& wsv : wsmr.out) type_spaces = std::max(type_spaces, wsv.size());
  for (auto& wsv : wsmr.in) type_spaces = std::max(type_spaces, wsv.size());
  for (auto& wsv : wsmr.gout) type_spaces = std::max(type_spaces, wsv.size());
  for (auto& wsv : wsmr.gin) type_spaces = std::max(type_spaces, wsv.size());
  const std::string spaces(name.size() + 3, ' ');

  std::string out = "  " + name + "(";

  std::string sep       = "";
  std::string other_sep = ",\n" + spaces;

  for (auto& wsv : wsmr.out) {
    out += std::format("{}{}{} : {}",
                       std::exchange(sep, other_sep),
                       wsv,
                       std::string(type_spaces - wsv.size(), ' '),
                       wsvs.at(wsv).type);
  }

  for (auto& wsv : wsmr.in) {
    if (stdr::any_of(wsmr.out, Cmp::eq(wsv))) continue;
    out += std::format("{}{}{} : {}",
                       std::exchange(sep, other_sep),
                       wsv,
                       std::string(type_spaces - wsv.size(), ' '),
                       wsvs.at(wsv).type);
  }

  for (std::size_t i = 0; i < wsmr.gout.size(); i++) {
    out += std::format("{}{}{} : {}",
                       std::exchange(sep, other_sep),
                       wsmr.gout[i],
                       std::string(type_spaces - wsmr.gout[i].size(), ' '),
                       wsmr.gout_type[i]);
  }

  for (std::size_t i = 0; i < wsmr.gin.size(); i++) {
    if (stdr::any_of(wsmr.gout, Cmp::eq(wsmr.gin[i]))) continue;
    out += std::format("{}{}{} : {}",
                       std::exchange(sep, other_sep),
                       wsmr.gin[i],
                       std::string(type_spaces - wsmr.gin[i].size(), ' '),
                       wsmr.gin_type[i]);
  }

  return out + ')';
}

void call_function(std::ostream& os, const std::string& name, const WorkspaceMethodInternalRecord& wsmr) try {
  const auto& wsv = internal_workspace_variables();

  {
    os << "[](Workspace& _ws [[maybe_unused]], const std::vector<std::string>& _out [[maybe_unused]], const std::vector<std::string>& _in [[maybe_unused]]) {\n";
    os << "    try {\n";

    // Look every variable up once.  The workspace is keyed by runtime strings, so
    // the checks share the lookups of the call rather than repeating them.
    int out_count = 0;
    for (auto& str : wsmr.out) {
      const bool inout = std::count(wsmr.in.begin(), wsmr.in.end(), str) != 0;
      os << "      auto& " << str << " = _ws.get" << (inout ? "" : "_or") << "<" << wsv.at(str).type << ">(_out["
         << out_count++ << "]);\n";
    }

    for (std::size_t i = 0; i < wsmr.gout.size(); i++) {
      const auto type = WorkspaceMethodInternalRecord::generic_type(wsmr.gout_type[i], true);
      if (type != wsmr.gout_type[i])
        os << "      auto " << wsmr.gout[i] << " = " << type << "::from(_ws.share(_out[" << out_count++ << "]));\n";
      else
        os << "      auto& " << wsmr.gout[i] << " = _ws.get_or<" << type << ">(_out[" << out_count++ << "]);\n";
    }

    int in_count = 0;
    for (auto& str : wsmr.in) {
      if (std::any_of(wsmr.out.begin(), wsmr.out.end(), [&str](auto& var) { return str == var; })) {
        in_count++;
        continue;
      }
      os << "      const auto& " << str << " = _ws.get<" << wsv.at(str).type << ">(_in[" << in_count++ << "]);\n";
    }

    for (std::size_t i = 0; i < wsmr.gin.size(); i++) {
      const auto index = in_count++;
      if (stdr::find(wsmr.gout, wsmr.gin[i]) != wsmr.gout.end()) continue;
      const auto type = WorkspaceMethodInternalRecord::generic_type(wsmr.gin_type[i]);
      if (type != wsmr.gin_type[i])
        os << "      const auto " << wsmr.gin[i] << " = " << type << "::from(_ws.share(_in[" << index << "]));\n";
      else
        os << "      const auto& " << wsmr.gin[i] << " = _ws.get<" << type << ">(_in[" << index << "]);\n";
    }

    auto pre = method_input_invariants(wsmr);
    std::ranges::move(method_input_size_checks(wsmr), std::back_inserter(pre));
    os << size_check_code(pre, "      ");

    bool first = true;
    os << "      " << name << "(";
    if (wsmr.pass_workspace) {
      os << "_ws";
      first = false;
    }

    const String spaces(name.size() + 7, ' ');

    for (auto& str : wsmr.out) { os << comma(first, spaces) << str; }

    for (const auto& g : wsmr.gout) { os << comma(first, spaces) << g; }

    for (auto& str : wsmr.in) {
      if (std::any_of(wsmr.out.begin(), wsmr.out.end(), [&str](auto& var) { return str == var; })) continue;
      os << comma(first, spaces) << str;
    }

    for (const auto& g : wsmr.gin) {
      if (stdr::find(wsmr.gout, g) != wsmr.gout.end()) continue;
      os << comma(first, spaces) << g;
    }

    os << "\n      );\n";

    os << size_check_code(method_output_size_checks(wsmr), "      ");

    os << "    } catch (std::exception& e) {\n"
          "      throw std::runtime_error(std::format(R\"-x-(Error in agenda call to specific method\n\n"
       << error_signature(name, wsmr)
       << "\n\n{})-x-\", e.what()));\n"
          "    }\n  }\n";
  }
} catch (std::exception& e) { throw std::runtime_error("Error in call_function():\n\n" + std::string(e.what())); }

void wsm_record(std::ostream& os, const std::string& name, const WorkspaceMethodInternalRecord& wsmr) try {
  os << "    .out={";
  bool first = true;
  for (auto& str : wsmr.out) { os << comma(first, "          ") << "\"" << str << "\""; }
  for (auto& str : wsmr.gout) { os << comma(first, "          ") << "\"_" << str << "\""; }
  os << "},\n";
  os << "    .in={";
  first = true;
  for (auto& str : wsmr.in) { os << comma(first, "         ") << "\"" << str << "\""; }
  for (auto& str : wsmr.gin) { os << comma(first, "         ") << "\"_" << str << "\""; }
  os << "},\n";
  os << "    .defs={";
  first = true;
  for (std::size_t i = 0; i < wsmr.gin.size(); i++) {
    if (wsmr.gin_value[i]) {
      os << comma(first, "           ") << "{\"_" << wsmr.gin[i] << "\", internal_workspace_methods().at(\"" << name
         << "\").gin_value[" << i << "].value()}";
    }
  }
  os << "},\n";

  os << "    .func=";
  call_function(os, name, wsmr);

  os << "\n";
} catch (std::exception& e) { throw std::runtime_error("Error in wsm_record():\n\n" + std::string(e.what())); }

void meta_implementation(std::ostream& os) try {
  const auto& wsm = internal_workspace_methods();

  os << R"--(//! auto-generated by make_auto_wsm.cpp

#include <workspace.h>
#include <workspace_meta_methods.h>

static const auto& _wsmmeta = internal_meta_methods();

)--";

  for (auto& m : internal_meta_methods()) { os << m.call(wsm) << '\n' << '\n'; }
} catch (std::exception& e) { throw std::runtime_error("Error in meta_implementation:\n\n" + std::string(e.what())); }

std::ofstream& select_ofstream(std::vector<std::ofstream>& ofs, int i) { return ofs[i % ofs.size()]; }

void implementation(std::ostream& os, const int n) try {
  const auto& wsm = internal_workspace_methods();

  std::vector<std::ofstream> ofs;
  ofs.reserve(n);
  for (int i = 0; i < n; i++) { ofs.emplace_back(std::format("auto_wsm_{}.cpp", i)); }

  for (auto& of : ofs) {
    of << R"--(//! auto-generated by make_auto_wsm.cpp

#include <iomanip>

#include "auto_wsm.h"

#include "workspace_methods.h"

#include "workspace_agenda_class.h"
#include "workspace_method_class.h"

#include "workspace_class.h"
#include <workspace.h>


)--";
  }

  int i = 0;
  for (auto& [name, wsmr] : wsm) {
    select_ofstream(ofs, i) << "WorkspaceMethodRecord _wsm_" << name << "() {\n  return {\n";
    wsm_record(select_ofstream(ofs, i), name, wsmr);
    select_ofstream(ofs, i) << "  };\n}\n\n";
    i++;
  }

  for (i = 0; i < n; i++) {
    select_ofstream(ofs, i) << "std::unordered_map<std::string, WorkspaceMethodRecord> get_workspace_methods" << i
                            << R"--(() {
  return {
)--";
  }

  i = 0;
  for (auto& [name, wsmr] : wsm) { select_ofstream(ofs, i++) << "    { \"" << name << "\", _wsm_" << name << "()},\n"; }

  for (auto& of : ofs)
    of << R"--(  };
}
)--";

  os << "#include \"auto_wsv.h\"\n\n";
  os << "#include <workspace.h>\n\n";
  for (i = 0; i < n; i++) {
    os << "std::unordered_map<std::string, WorkspaceMethodRecord> get_workspace_methods" << i << "();\n";
  }
  os << R"--(
const std::unordered_map<std::string, WorkspaceMethodRecord>& workspace_methods() {
  static std::unordered_map<std::string, WorkspaceMethodRecord> wsm;
  static bool first = true;
  if (first) {
    first = false;
)--";

  for (i = 0; i < n; i++) {
    os << "    const std::unordered_map<std::string, WorkspaceMethodRecord> m" << i << " = get_workspace_methods" << i
       << "();\n    const std::size_t n" << i << " = m" << i << ".size();\n";
  }
  os << "\n    wsm.reserve(";
  for (i = 0; i < n; i++) { os << "n" << i << " + "; }
  os << "0);\n\n";
  for (i = 0; i < n; i++) {
    os << R"--(    for (auto& [k, v] : m)--" << i << R"--() {  wsm[k] = v; }
)--";
  }

  os << R"--(
  }
  return wsm;
}
)--";
} catch (std::exception& e) { throw std::runtime_error("Error in implementation():\n\n" + std::string(e.what())); }

void various_checks_or_throw() {
  ArrayOfString errors{};
  for (auto& [name, wsmr] : internal_workspace_methods()) {
    bool is_void = wsmr.return_type == "void";
    if (not is_void) {
      bool is_workspace  = wsmr.return_type == "Workspace";
      bool is_wsg        = internal_workspace_groups().contains(wsmr.return_type);
      bool is_wsg_friend = workspace_group_friends().contains(wsmr.return_type);
      if (not is_workspace and not is_wsg and not is_wsg_friend) {
        errors.push_back(std::format(
            "Method {} has a return type.  Its return type \"{}\" is not void or Workspace, and it is not a workspace group (or friend of one).",
            name,
            wsmr.return_type));
      }

      if (wsmr.return_desc.empty()) {
        errors.push_back(std::format("Method {} has a return type.  It lacks a return description.", name));
      }
    }
  }

  if (not errors.empty()) {
    throw std::runtime_error(std::format("Errors found in workspace methods:\n\n{:n}", errors));
  }
}
}  // namespace

int main(int argc, char** argv) try {
  if (argc != 2) throw std::runtime_error("usage: make_auto_wsm <num_methods>");

  various_checks_or_throw();

  const int     num_methods = std::stoi(argv[1]);
  std::ofstream head("auto_wsm.h");
  std::ofstream impl("auto_wsm.cpp");
  std::ofstream of("auto_wsmmeta.cpp");

  ARTS_USER_ERROR_IF(const auto err = scan_for_errors(); not err.empty(), "{}", err)

  header(head);
  implementation(impl, num_methods);
  meta_implementation(of);
} catch (std::exception& e) {
  std::cerr << "Cannot create the automatic methods with error:\n\n" << e.what() << '\n';
  return 1;
}
