#pragma once

// Internal data
#include "workspace_agendas.h"
#include "workspace_groups.h"
#include "workspace_methods.h"
#include "workspace_variables.h"
#include "workspace_variables_keywords.h"

// Core logic
#include "workspace_agenda_class.h"
#include "workspace_agenda_creator.h"
#include "workspace_class.h"
#include "workspace_method_class.h"

// Autogenerated helpers
#include <auto_wsa.h>
#include <auto_wsg.h>
#include <auto_wsm.h>
#include <auto_wsv.h>

// For help
#include <time_report.h>

