name: Download testdata

on: [push, pull_request]

jobs:
  prepare:
    name: Prepare testdata
    runs-on: ubuntu-latest
    steps:
      - name: Check Runner IP
        run: |
          echo "Runner public IP:"
          curl -s https://api.ipify.org
          echo
          echo
          echo "Test testdata server access:"
          curl -o /dev/null --no-progress-meter https://arts.mi.uni-hamburg.de/svn/rt/arts-xml-data/trunk/planets/Earth/afgl/readme.txt && echo "OK" || echo "FAIL"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Download xml testdata
        run: |
          python3 testdata/get_testdata.py testdata/xml_data_files.txt build/testdata

      - name: Download cat testdata
        run: |
          python3 testdata/get_testdata.py testdata/cat_data_files.txt build/testdata

      - name: Upload testdata artifact
        uses: actions/upload-artifact@v4
        with:
          name: testdata
          path: build/
          retention-days: 1
  build:
    name: Build
    needs: prepare
    uses: ./.github/workflows/build-test.yml
